/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/campaigns": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Campaigns */
    get: operations["campaigns_v1_campaigns_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/campaigns/{campaign_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Campaign Detail */
    get: operations["campaign_detail_v1_campaigns__campaign_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/campaigns/{campaign_id}/submissions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Campaign Submissions */
    get: operations["campaign_submissions_v1_campaigns__campaign_id__submissions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Stats */
    get: operations["stats_v1_stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/campaigns/{campaign_id}/leader": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Campaign Leader
     * @description The crown holder. A vacant crown has no row, so it is a 404.
     */
    get: operations["campaign_leader_v1_campaigns__campaign_id__leader_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/campaigns/{campaign_id}/rounds": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Campaign Rounds */
    get: operations["campaign_rounds_v1_campaigns__campaign_id__rounds_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/campaigns/{campaign_id}/score-progress": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Campaign Score Progress
     * @description Chart series, oldest ordinal first. Void rounds keep their ordinal.
     */
    get: operations["campaign_score_progress_v1_campaigns__campaign_id__score_progress_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rounds/{round_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Round Detail */
    get: operations["round_detail_v1_rounds__round_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rounds/{round_id}/entries/{entry_id}/report": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Round Entry Report
     * @description The arithmetic behind one entry's score, prompt by prompt.
     *
     *     The round score is the named rule applied to `prompts`, so a miner can
     *     re-derive it and see which prompts paid and which were gated. Absolute
     *     seconds are served alongside the ratios: a speedup on its own cannot be
     *     checked against a local run.
     *
     *     The baseline entry stores its SLA replay rather than a comparison, so it
     *     comes back with `sla` populated and `prompts` empty. It is the reference
     *     the rest are measured against, not a competitor with a score of its own.
     */
    get: operations["round_entry_report_v1_rounds__round_id__entries__entry_id__report_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/weights": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Latest Weights
     * @description The newest stored weight vector. Reads only; never computes.
     *
     *     `weights[i]` is UID `i`. Pass it to `SetWeights` with
     *     `uids=range(len(weights))`. A missing or all-zero row is 404: an empty
     *     vector is a valid on-chain instruction to pay nobody.
     */
    get: operations["latest_weights_v1_weights_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/campaigns/{campaign_id}/submissions/{patch_hash}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Campaign Submission Detail */
    get: operations["campaign_submission_detail_v1_campaigns__campaign_id__submissions__patch_hash__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/submissions/{patch_hash}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Submission Detail */
    get: operations["submission_detail_v1_submissions__patch_hash__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/campaigns/{campaign_id}/submissions/{patch_hash}/patch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Campaign Submission Patch */
    get: operations["campaign_submission_patch_v1_campaigns__campaign_id__submissions__patch_hash__patch_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/submissions/{patch_hash}/patch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Submission Patch */
    get: operations["submission_patch_v1_submissions__patch_hash__patch_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/campaigns/{campaign_id}/submissions/{patch_hash}/build-log": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Campaign Submission Build Log */
    get: operations["campaign_submission_build_log_v1_campaigns__campaign_id__submissions__patch_hash__build_log_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/submissions/{patch_hash}/build-log": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Submission Build Log
     * @description Last `tail` lines of the durable build log (PAR-37 path), sanitized.
     *
     *     Content is miner-influenced build output: ANSI/control chars stripped,
     *     served as text/plain. Non-terminal submissions are Cache-Control: no-store
     *     so live tails are not held by CDN/browser caches (PAR-44).
     */
    get: operations["submission_build_log_v1_submissions__patch_hash__build_log_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/uploads/patch": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Presign Patch */
    post: operations["presign_patch_v1_uploads_patch_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * BenchPhase
     * @description Current operation. Multi-SKU runs cycle, so this is not monotonic.
     * @enum {string}
     */
    BenchPhase:
      | "provisioning"
      | "bootstrapping"
      | "pulling_image"
      | "downloading_model"
      | "starting_engine"
      | "correctness"
      | "sla_bench"
      | "teardown";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * LeaderModel
     * @description `GET /v1/campaigns/{campaign_id}/leader`. Detail page: full hotkey.
     */
    LeaderModel: {
      /** Campaign Id */
      campaign_id: string;
      /** Submission Id */
      submission_id: string;
      /** Patch Hash */
      patch_hash: string;
      /** Hotkey */
      hotkey: string;
      /** Engine Image Ref */
      engine_image_ref: string;
      /** Won At Round Id */
      won_at_round_id: string;
      /** Won At Ordinal */
      won_at_ordinal: number;
      /** Last Score */
      last_score: number;
      /** Last Scored Round Id */
      last_scored_round_id?: string | null;
      /** Updated At */
      updated_at: string;
    };
    /** PresignRequest */
    PresignRequest: {
      /**
       * Campaign Id
       * Format: uuid
       */
      campaign_id: string;
      /** Hotkey */
      hotkey: string;
      /** Patch Hash */
      patch_hash: string;
      /**
       * Upload Id
       * Format: uuid4
       */
      upload_id: string;
      /** Expires At */
      expires_at: number;
      /** Network */
      network: string;
      /** Netuid */
      netuid: number;
      /** Signature */
      signature: string;
    };
    /** PresignResponse */
    PresignResponse: {
      /** Upload Url */
      upload_url: string;
      /** Retrieval Url */
      retrieval_url: string;
      /** Object Key */
      object_key: string;
      /** Expires In */
      expires_in: number;
      /** Required Headers */
      required_headers: {
        [key: string]: string;
      };
      /**
       * Already Uploaded
       * @default false
       */
      already_uploaded: boolean;
    };
    /**
     * PromptScoreModel
     * @description One prompt's contribution to an entry's score.
     *
     *     `speedup` is the fraction faster than baseline at the same output token
     *     count: 0.35 is 35 percent faster, and a negative value is slower. A
     *     non-null `reason` means the prompt was forced to 0.0 and did not measure
     *     anything; a 0.0 with no reason is a real result meaning baseline speed.
     */
    PromptScoreModel: {
      /** Request Id */
      request_id: string;
      /** Speedup */
      speedup: number;
      /** Aligned Tokens */
      aligned_tokens: number;
      /** Baseline E2E S */
      baseline_e2e_s?: number | null;
      /** Candidate E2E S */
      candidate_e2e_s?: number | null;
      /** Reason */
      reason?: string | null;
      /** Candidate Failed */
      candidate_failed?: boolean | null;
      /** Input Tokens */
      input_tokens?: number | null;
      /** Max Tokens */
      max_tokens?: number | null;
      /** Input Length Group */
      input_length_group?: string | null;
    };
    /**
     * PromptSummaryModel
     * @description Counts over `prompts`, so the headline number needs no client math.
     */
    PromptSummaryModel: {
      /** Total */
      total: number;
      /** Scored */
      scored: number;
      /** Zeroed */
      zeroed: number;
      /** Below Tolerance */
      below_tolerance: number;
      /** Zeroed By Reason */
      zeroed_by_reason: {
        [key: string]: number;
      };
    };
    /** ReportWorkloadModel */
    ReportWorkloadModel: {
      /** Temperature */
      temperature?: number | null;
      /** Temperature Range */
      temperature_range?: number[] | null;
      /** Algo Version */
      algo_version: number;
      /** Request Interval Ms */
      request_interval_ms: number;
      /** Enable Thinking */
      enable_thinking?: boolean | null;
      /** Max Model Len */
      max_model_len?: number | null;
    };
    /**
     * RoundDetailModel
     * @description `GET /v1/rounds/{round_id}`. `phase` is live while the round runs.
     */
    RoundDetailModel: {
      /** Id */
      id: string;
      /** Campaign Id */
      campaign_id: string;
      /** Ordinal */
      ordinal: number;
      /** Status */
      status: string;
      /** Void Reason */
      void_reason?: string | null;
      /** Void Detail */
      void_detail?: string | null;
      /** Gpu Sku */
      gpu_sku: string;
      /** Seed Block */
      seed_block: number;
      /** Seed Block Hash */
      seed_block_hash: string;
      /** Seed Hex */
      seed_hex: string;
      /** Sampled Trace Sha256 */
      sampled_trace_sha256: string;
      /** Scoring Rule */
      scoring_rule: {
        [key: string]: unknown;
      };
      /** Incumbent Submission Id */
      incumbent_submission_id?: string | null;
      /** Winner Submission Id */
      winner_submission_id?: string | null;
      /** Leader Changed */
      leader_changed?: boolean | null;
      /** Baseline Drift */
      baseline_drift?: number | null;
      /** Phase */
      phase?: components["schemas"]["BenchPhase"] | string | null;
      /** Phase Started At */
      phase_started_at?: string | null;
      /** Heartbeat At */
      heartbeat_at?: string | null;
      /** Progress */
      progress?: {
        [key: string]: unknown;
      } | null;
      /** Created At */
      created_at: string;
      /** Started At */
      started_at?: string | null;
      /** Completed At */
      completed_at?: string | null;
      /** Entries */
      entries: components["schemas"]["RoundEntryModel"][];
    };
    /**
     * RoundEntryModel
     * @description One image run inside a round. Evidence URLs stay behind their gate.
     *
     *     `role` and `status` are `round_entries` values; the vocabularies are
     *     `round.rank.ENTRY_ROLES` and `round.rank.ENTRY_STATUSES`. `score` is null
     *     for a disqualified or infra-failed entry; 0.0 means baseline speed.
     */
    RoundEntryModel: {
      /** Id */
      id: number;
      /** Submission Id */
      submission_id?: string | null;
      /** Patch Hash */
      patch_hash?: string | null;
      /** Hotkey */
      hotkey?: string | null;
      /** Role */
      role: string;
      /** Engine Image Ref */
      engine_image_ref: string;
      /** Status */
      status: string;
      /** Score */
      score?: number | null;
      /** Disqualify Reason */
      disqualify_reason?: string | null;
      /** Started At */
      started_at?: string | null;
      /** Completed At */
      completed_at?: string | null;
    };
    /**
     * RoundEntryReportModel
     * @description `GET /v1/rounds/{round_id}/entries/{entry_id}/report`.
     *
     *     The arithmetic behind one entry's score. `prompts` is empty for an entry
     *     that never reached scoring, which is every disqualified and infra-failed
     *     entry: read `status` and `reason` for why.
     */
    RoundEntryReportModel: {
      /** Round Id */
      round_id: string;
      /** Round Ordinal */
      round_ordinal: number;
      /** Entry Id */
      entry_id: number;
      /** Submission Id */
      submission_id?: string | null;
      /** Patch Hash */
      patch_hash?: string | null;
      /** Hotkey */
      hotkey?: string | null;
      /** Role */
      role: string;
      /** Status */
      status: string;
      /** Engine Image Ref */
      engine_image_ref: string;
      /** Image Digest */
      image_digest?: string | null;
      /** Score */
      score?: number | null;
      /** Reason */
      reason?: string | null;
      /**
       * Engine Crashed
       * @default false
       */
      engine_crashed: boolean;
      /** Scoring Rule */
      scoring_rule: {
        [key: string]: unknown;
      };
      prompt_summary: components["schemas"]["PromptSummaryModel"];
      score_breakdown?: components["schemas"]["ScoreBreakdownModel"] | null;
      workload?: components["schemas"]["ReportWorkloadModel"] | null;
      /** Prompts */
      prompts: components["schemas"]["PromptScoreModel"][];
      /** Sla */
      sla?: {
        [key: string]: unknown;
      } | null;
      /** Correctness */
      correctness?: {
        [key: string]: unknown;
      } | null;
      /** Started At */
      started_at?: string | null;
      /** Completed At */
      completed_at?: string | null;
    };
    /**
     * RoundSummaryModel
     * @description One row of `GET /v1/campaigns/{campaign_id}/rounds`.
     */
    RoundSummaryModel: {
      /** Id */
      id: string;
      /** Ordinal */
      ordinal: number;
      /** Status */
      status: string;
      /** Void Reason */
      void_reason?: string | null;
      /** Void Detail */
      void_detail?: string | null;
      /** Gpu Sku */
      gpu_sku: string;
      /** Seed Block */
      seed_block: number;
      /** Seed Block Hash */
      seed_block_hash: string;
      /** Entry Count */
      entry_count: number;
      /** Leader Changed */
      leader_changed?: boolean | null;
      /** Created At */
      created_at: string;
      /** Completed At */
      completed_at?: string | null;
    };
    /** RoundsPageModel */
    RoundsPageModel: {
      /** Campaign Id */
      campaign_id: string;
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Rounds */
      rounds: components["schemas"]["RoundSummaryModel"][];
    };
    /** ScoreBreakdownModel */
    ScoreBreakdownModel: {
      /** Median Speedup */
      median_speedup: number;
      /** Scheduled Requests */
      scheduled_requests: number;
      /** Failed Requests */
      failed_requests: number;
      /** Failure Rate */
      failure_rate: number;
      /** Failure Penalty */
      failure_penalty: number;
      /** Penalty */
      penalty: number;
    };
    /**
     * ScorePointEntryModel
     * @description One scatter dot. List response, so the hotkey is truncated.
     */
    ScorePointEntryModel: {
      /** Submission Id */
      submission_id: string;
      /** Hotkey */
      hotkey?: string | null;
      /** Role */
      role: string;
      /** Status */
      status: string;
      /** Score */
      score?: number | null;
    };
    /**
     * ScorePointModel
     * @description One round ordinal on the chart. A void round leaves a gap, not a zero.
     */
    ScorePointModel: {
      /** Round Id */
      round_id: string;
      /** Ordinal */
      ordinal: number;
      /** Status */
      status: string;
      /** Leader Score */
      leader_score?: number | null;
      /** Entries */
      entries: components["schemas"]["ScorePointEntryModel"][];
    };
    /** ScoreProgressModel */
    ScoreProgressModel: {
      /** Campaign Id */
      campaign_id: string;
      /** Points */
      points: components["schemas"]["ScorePointModel"][];
    };
    /**
     * SubmissionDetailModel
     * @description `submission` stays loose: no state field, no payoff.
     */
    SubmissionDetailModel: {
      /** Submission */
      submission: {
        [key: string]: unknown;
      };
      /** Latest State */
      latest_state?: components["schemas"]["SubmissionState"] | string | null;
      /** Jobs */
      jobs: components["schemas"]["SubmissionJobModel"][];
      /** Events */
      events: components["schemas"]["SubmissionEventModel"][];
      round?: components["schemas"]["SubmissionRoundModel"] | null;
    };
    /** SubmissionEventModel */
    SubmissionEventModel: {
      /** State */
      state: components["schemas"]["SubmissionState"] | string;
      /** Evidence Ref */
      evidence_ref?: string | null;
      /** Detail */
      detail?: {
        [key: string]: unknown;
      };
      /** Created At */
      created_at: string;
    };
    /** SubmissionJobModel */
    SubmissionJobModel: {
      /** Status */
      status: string;
      /** Last Error */
      last_error?: string | null;
      /** Phase */
      phase?: components["schemas"]["BenchPhase"] | string | null;
      /** Phase Started At */
      phase_started_at?: string | null;
      /** Heartbeat At */
      heartbeat_at?: string | null;
      /** Progress */
      progress?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * SubmissionRoundModel
     * @description A submission's newest round entry: where it ran and how it did.
     *
     *     `status` is the entry verdict (`round_entries.status`). A submission that
     *     never reached a round has no model at all, and `rejected` is reported by
     *     `latest_state`: a rejected submission never got an entry.
     */
    SubmissionRoundModel: {
      /** Round Id */
      round_id: string;
      /** Ordinal */
      ordinal: number;
      /** Status */
      status: string;
      /** Score */
      score?: number | null;
      /** Disqualify Reason */
      disqualify_reason?: string | null;
    };
    /**
     * SubmissionState
     * @description The pipeline state vocabulary. This is the only definition.
     *
     *     `campaign.store.KNOWN_SUBMISSION_STATES`, the OpenAPI schema, and the
     *     frontend `SubmissionState` union all derive from these members. Adding a
     *     state here is the whole change on the backend. Member order is the pipeline
     *     order and is used for `/v1/stats` bucket ordering, so append new states in
     *     the position the worker reaches them.
     * @enum {string}
     */
    SubmissionState:
      | "committed"
      | "picked_up"
      | "fetched"
      | "verified"
      | "applied"
      | "surface_ok"
      | "building"
      | "image_pushed"
      | "built"
      | "bench_queued"
      | "round_assigned"
      | "infra_failed"
      | "scored"
      | "disqualified"
      | "rejected"
      | "rejected_duplicate";
    /**
     * SubmissionSummaryModel
     * @description One row of `GET /v1/campaigns/{campaign_id}/submissions`.
     */
    SubmissionSummaryModel: {
      /** Id */
      id: string;
      /** Campaign Id */
      campaign_id: string;
      /** Patch Hash */
      patch_hash: string;
      /** Hotkey */
      hotkey: string;
      /** Baseline Commit */
      baseline_commit: string;
      /** Retrieval Url */
      retrieval_url: string;
      /** Commit Block */
      commit_block?: number | null;
      /** Committed At */
      committed_at: string;
      /** Engine Image Ref */
      engine_image_ref?: string | null;
      /** Latest State */
      latest_state?: components["schemas"]["SubmissionState"] | string | null;
      round?: components["schemas"]["SubmissionRoundModel"] | null;
      /** Patch Reveal At */
      patch_reveal_at?: string | null;
      /** Patch Download Url */
      patch_download_url?: string | null;
    };
    /** SubmissionsPageModel */
    SubmissionsPageModel: {
      /** Campaign Id */
      campaign_id: string;
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Submissions */
      submissions: components["schemas"]["SubmissionSummaryModel"][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
    /**
     * WeightBreakdownModel
     * @description One campaign's contribution, so the vector is auditable, not magic.
     *
     *     `uid` is what the metagraph reported at compute time and is NOT
     *     authoritative afterwards: a UID is a lease that deregistration reassigns,
     *     so nobody may cache it. Resolve a hotkey against the live metagraph.
     *
     *     `note` says why a share was withheld (`vacant`, `closed`, `deregistered`)
     *     and is null for a share that paid. A withheld share burns.
     */
    WeightBreakdownModel: {
      /** Campaign Id */
      campaign_id: string;
      /** Hotkey */
      hotkey?: string | null;
      /** Uid */
      uid?: number | null;
      /** Blocks Held */
      blocks_held?: number | null;
      /** Weight */
      weight: number;
      /** Note */
      note?: string | null;
    };
    /**
     * WeightsModel
     * @description `GET /v1/weights`. `weights[i]` is the weight for UID `i`.
     */
    WeightsModel: {
      /** Computed At Block */
      computed_at_block: number;
      /** Version Key */
      version_key: number;
      /** Burn Uid */
      burn_uid: number;
      /** Weights */
      weights: number[];
      /** Breakdown */
      breakdown: components["schemas"]["WeightBreakdownModel"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  campaigns_v1_campaigns_get: {
    parameters: {
      query?: {
        status?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  campaign_detail_v1_campaigns__campaign_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  campaign_submissions_v1_campaigns__campaign_id__submissions_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        campaign_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubmissionsPageModel"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  stats_v1_stats_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  campaign_leader_v1_campaigns__campaign_id__leader_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LeaderModel"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  campaign_rounds_v1_campaigns__campaign_id__rounds_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        campaign_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RoundsPageModel"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  campaign_score_progress_v1_campaigns__campaign_id__score_progress_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScoreProgressModel"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  round_detail_v1_rounds__round_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        round_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RoundDetailModel"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  round_entry_report_v1_rounds__round_id__entries__entry_id__report_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        round_id: string;
        entry_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RoundEntryReportModel"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  latest_weights_v1_weights_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["WeightsModel"];
        };
      };
    };
  };
  campaign_submission_detail_v1_campaigns__campaign_id__submissions__patch_hash__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: string;
        patch_hash: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubmissionDetailModel"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submission_detail_v1_submissions__patch_hash__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        patch_hash: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SubmissionDetailModel"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  campaign_submission_patch_v1_campaigns__campaign_id__submissions__patch_hash__patch_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        campaign_id: string;
        patch_hash: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submission_patch_v1_submissions__patch_hash__patch_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        patch_hash: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  campaign_submission_build_log_v1_campaigns__campaign_id__submissions__patch_hash__build_log_get: {
    parameters: {
      query?: {
        tail?: number;
      };
      header?: never;
      path: {
        campaign_id: string;
        patch_hash: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submission_build_log_v1_submissions__patch_hash__build_log_get: {
    parameters: {
      query?: {
        tail?: number;
      };
      header?: never;
      path: {
        patch_hash: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  presign_patch_v1_uploads_patch_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PresignRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PresignResponse"];
        };
      };
      /** @description Invalid upload authorization or disqualified hotkey */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Upload UUID already contains a different patch */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
